version: '3'
services:
  bot:
    build: .
    restart: always
    environment:
      MONGO_URL: 'mongodb://mongo-auth:g7iqVbMSTHumk4p9KkK@mongo:27017/?authMechanism=SCRAM-SHA-1'
      BOT_TOKEN: 'MTE1ODQ0NDM0OTAwOTQyODYyNA.GTG0Gc.zt_W0vcLzMZlSNnp64tO1j4bK_UZEFecuwP7e0'
    links:
      - mongo
    networks:
      - teebot
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - teebot-data:/data/db
    networks:
      - teebot
    expose:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-auth
      MONGO_INITDB_ROOT_PASSWORD: g7iqVbMSTHumk4p9KkK
  mongo-express:
    image: mongo-express
    restart: always
    expose:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-auth
      ME_CONFIG_MONGODB_ADMINPASSWORD: g7iqVbMSTHumk4p9KkK
      ME_CONFIG_MONGODB_URL: mongodb://mongo-auth:g7iqVbMSTHumk4p9KkK@mongo:27017/?authMechanism=SCRAM-SHA-1
    links:
      - mongo
    networks:
      - teebot
    depends_on:
      - mongo
volumes:
  teebot-data:
networks:
  teebot: